[
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812725772.144136,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GA1.1.2092490730.1770214179",
        "id": 1
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812717651.008827,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_BF8Q35BMLM",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778157650$o138$g0$t1778157650$j60$l0$h0",
        "id": 2
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1812725772.141046,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_WC57KJ50ZZ",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "GS2.1.s1778165772$o174$g0$t1778165772$j60$l0$h0",
        "id": 3
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1782639016,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_au",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "1.1.792299493.1774863016",
        "id": 4
    },
    {
        "domain": ".gemini.google.com",
        "expirationDate": 1779021643.445877,
        "hostOnly": false,
        "httpOnly": true,
        "name": "COMPASS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "gemini-pd=CjwACWuJV93jFYb_b6k1ZbZc5AVi75OXfwVJx6huPFdJgLZgT-iphNSBtyIyTho-2Gurv4U86El7hPmdVFUQ0LP3zwYaZgAJa4lXpMUDqFVhvXayopoShCupMZ4RLawHcFAuWARBhjOrJVB-3oEU5wtdV15b1EOYQIe5hCZ5DOD3piSo-ZbfYWH1mTJFE16T8V-uVuY9jDm0hClnGxrMB8giX_tZwhmSaQx2JiABMAE:gemini-hl=CkkACWuJV4Jq7gXnYGXm-CCWRGf1MNczIJ0yMsen8R98zb0fdd_v1HDcw_-Y0Gxw7WZu_GGVl89NUAGecp6EG6tM_DjudIlkdiK-EIrY7M8GGnMACWuJV31T-KTfj_kfyrGQHbGXZ7KunpXW6SzAgefOWjjwyayg6Iwu0SbTAuaaMQSQ8ufFGG6iBo8LYRPIidrB1YJS53ezUMIrhyU-FP7Nc8Boi7MnVyvN6x2wVXePw5OBeTd2MJhE9RaLVXVvihLIkRdpIAEwAQ",
        "id": 5
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760433,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-1PAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 6
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758956,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykElIlJU5gpR1Ai10pJezZ-OwACgYKAXISARESFQHGX2MiCVnL1NihqvD4LnuV0MvnjRoVAUF8yKrB8z8U8DweF9bo8g-g8wS20076",
        "id": 7
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809701773.969781,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzWAoux6QUa2dEjZB7883wcv3MVplEMBxyHec4rV2IVDLoA17OdCKsTq4n7HzWxwPP02Ycc",
        "id": 8
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778166151.652061,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDRTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRdxL--mCA2SX1ipE2A8bI9YViTR_22FH3KoOASuJzSrM1GjElFTHye1uMdBM63HawZjEQAA",
        "id": 9
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809701551.65185,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-1PSIDTS",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRdxL--mCA2SX1ipE2A8bI9YViTR_22FH3KoOASuJzSrM1GjElFTHye1uMdBM63HawZjEQAA",
        "id": 10
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760542,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-3PAPISID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 11
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759207,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykEKhEpDvOfxNfv1gnzVhDgLgACgYKAWsSARESFQHGX2MiIwf6hYr88_aIGDSFLiAoQxoVAUF8yKqRZuK5eO2tinjqLjyjgesF0076",
        "id": 12
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809701773.970068,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDCC",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzVR4XUS0w1Yoz5WohqiumuMQhoJBoeeumnjSZ5a6CmFyekg2ApojZN2k9NGnZoJMTyfK8qw",
        "id": 13
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778166151.65224,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDRTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRdxL--mCA2SX1ipE2A8bI9YViTR_22FH3KoOASuJzSrM1GjElFTHye1uMdBM63HawZjEQAA",
        "id": 14
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809701551.65215,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-3PSIDTS",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "sidts-CjYBhkeRdxL--mCA2SX1ipE2A8bI9YViTR_22FH3KoOASuJzSrM1GjElFTHye1uMdBM63HawZjEQAA",
        "id": 15
    },
    {
        "domain": ".google.com",
        "expirationDate": 1783131940.378771,
        "hostOnly": false,
        "httpOnly": true,
        "name": "__Secure-BUCKET",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "CPoD",
        "id": 16
    },
    {
        "domain": ".google.com",
        "expirationDate": 1778165839.925475,
        "hostOnly": false,
        "httpOnly": false,
        "name": "__Secure-STRP",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AEEP7gK-yq4W6JWlU-rM6KNFsBG7WBWMG8Tdg1c9IqmNxTFqY8kUU9YW95Vl__90zXgMnJhnv_tQV--rPu3etxj__av6W4Zarw",
        "id": 17
    },
    {
        "domain": ".google.com",
        "expirationDate": 1779623964.925612,
        "hostOnly": false,
        "httpOnly": true,
        "name": "AEC",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AaJma5sjoHtK83BirO7ZAAAo_FS6Cj6xsPP0wTZC8lvUZSjrRaHfRvNqIF0",
        "id": 18
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760211,
        "hostOnly": false,
        "httpOnly": false,
        "name": "APISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "RI-HjCC3Ay9zGYNG/AmG8_CYsDra4vDn6D",
        "id": 19
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.759938,
        "hostOnly": false,
        "httpOnly": true,
        "name": "HSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AzNF-yxlSqbjf5wAD",
        "id": 20
    },
    {
        "domain": ".google.com",
        "expirationDate": 1793968841.49407,
        "hostOnly": false,
        "httpOnly": true,
        "name": "NID",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "531=NlR88jRadKnXmqgNxJzVbR0AXLiiIrWcYQDwjK8AqMKOlrk79ye8rn-B_LaR3QIOixW9Ncjsl8LHzpVgfq_QRE31wZfD8NmWXiHrBeVxuWy_5DxwAqt-H2VVKi124utT9Nb_AqMPMw5uX24JzxxuHgriqwTHh7ft0Heim61g9pyCR15p3_tb_dgy6BVtPuC1-RR1dV8ah81gYGqdEZuls8zUC49ZD6q6PAPLupQFfDzkm8pU6HCKYovWNB1KzeXT6_qj3mEjpwC1dYM9PLi1GxJcdMhM2PnpIJTMElDV3JURhtYdFILhp2NR_po4vE1hy5zKTRh92qj_0OSSV6pHkUNiWLXxdTR0wXEyV14eYkb30Qqj2EWJkAx08wt0_aBv5CSrwjhJVHdm3B4WOoHwz1K4s7HXIL7f9SX0OneWVUxDlGcGhqhnYTriOZAQaeci3aIPq6uBVeVr853Y76OdYeAC9pFYrJUmBoOQmDBw6meUkSI2axw4gJsxHvPptN9mz4OCnzO6QJIMixcCg1vbXI328PmdzWlUxkU4lhZsxldYVUNIFVJy2BOmxQpvdUUTepfNAlSlAio9BptsK-pJDKSggY3mZ8Goqdxzz1d-etJxMQ8l5SalVMEiwkkoi1-lQNpDRjxyq4DPTE9b0N4YStEjptDggUhdeq1MwWRYlv_KF3MHcHNMUAW_X3qlZOEivqO3CXFJl60j1focnT9_2LuXdmQYMpg-NhCXhcedljpaRZwTAzfvCJQxKxAoTtLhHTV9WbbaUEJRyJMSuOXv07KWOTCjv_KQece6V96tBBejBx3JjsVazN3-yYHKT1q1fSFOn4DkxU3N-P3eJmmygo94NNkoe-eUGWrpixMoUolhk-s54oWubaJWDCKLLJUJxRknpqGbSWo8AMl1Kzj2zYXVr3l0tTg4Gf9Bjh1f_CYufvAdpVPhFDNAdtlzl-rOIfjhD4pOmHYK2RGtVHlsemASg7D2ffu2cWYbnnFovjFHRGTaNPfURO6ubl1-_Hcu6iyHxtt83ErWBHtlKLL9p26uHz5vyv8Fer-bDVCe7PCELhNNbYnFB0seBQHJcs8kUYJM3lKoBt4BjobMLVjsyjcZxDWrulNcFTc",
        "id": 21
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760328,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SAPISID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "Y9HV5Kc8cM8vTBN6/AtmURmzxOh87hbr_v",
        "id": 22
    },
    {
        "domain": ".google.com",
        "expirationDate": 1792574521.075714,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SEARCH_SAMESITE",
        "path": "/",
        "sameSite": "strict",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "CgQI16AB",
        "id": 23
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.758709,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "g.a0009QgRdowFVg6N3v6BpQPMjje79U-5QcNUBBs4ZRjnUujDzykETZBsrTE-HYdUo3ZIh7lI2AACgYKASsSARESFQHGX2MiY_mzE7jgdCX9PCDawjWQPxoVAUF8yKqyTjfBVJXBL5nglHyb4cVY0076",
        "id": 24
    },
    {
        "domain": ".google.com",
        "expirationDate": 1809701773.96948,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SIDCC",
        "path": "/",
        "sameSite": "unspecified",
        "secure": false,
        "session": false,
        "storeId": "0",
        "value": "AKEyXzXfjZKmeZKnDDN9iiQCNP7FRP-KARkdQHGimXhg1SCXNp4bHfBj_Ds1d3_zEiCo1DZUiDvX",
        "id": 25
    },
    {
        "domain": ".google.com",
        "expirationDate": 1812127959.760103,
        "hostOnly": false,
        "httpOnly": true,
        "name": "SSID",
        "path": "/",
        "sameSite": "unspecified",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "AATuRE3UZ6mCtv0ys",
        "id": 26
    }
]