import requests
import json
import re

SERVER_URL = "http://localhost:5679"

raw_text = """
[DÁN NỘI DUNG NGƯỜI DÙNG CUNG CẤP Ở ĐÂY - Tôi sẽ xử lý biến này trong script thực tế]
"""

# Dữ liệu mẫu bóc tách từ text người dùng
data_q2 = [
    # Part 1
    {"topic": "Watch", "questions": ["Do you wear a watch?", "Have you ever got a watch as a gift?", "Why do some people wear expensive watches?", "Do you think it is important to wear a watch? Why?"]},
    {"topic": "Cars", "questions": ["Do you think car colours are important?", "Did you enjoy traveling by car when you were a kid?", "What types of cars do you like?", "Do you prefer to be a driver or a passenger?", "What do you usually do when there is a traffic jam?"]},
    {"topic": "Websites", "questions": ["What kinds of websites do you often visit?", "What is your favourite website?", "Are there any changes to the websites you often visit?", "What kinds of websites are popular in your country?"]},
    {"topic": "Mirrors", "questions": ["Do you like looking at yourself in the mirror? How often?", "Have you ever bought mirrors?", "Do you usually take a mirror with you？", "Would you use mirrors to decorate your room?"]},
    {"topic": "Views", "questions": ["Do you like taking pictures of different views?", "Do you prefer views in urban areas or rural areas?", "Do you prefer views in your own country or in other countries?", "Have you seen an unforgettable and beautiful view or scenery?"]},
    {"topic": "Childhood activities", "questions": ["What are your favourite activities?", "What were your favourite activities when you were a child?", "Did you prefer to do activities alone or with a group of people when you were a child?", "Are there any differences between the activities you liked when you were a child and those you like now?"]},
    {"topic": "Building", "questions": ["Are there tall buildings near your home?", "Do you take photos of buildings?", "Is there a building that you would like to visit?"]},
    {"topic": "Scenery", "questions": ["Do you look out the window at the scenery when travelling by bus or car?", "Do you prefer the mountains or the sea?", "Do you like to take scenery pictures?", "What are the most beautiful sights you have seen while travelling?"]},
    {"topic": "Reading", "questions": ["Do you like reading?", "Do you prefer to read on paper or on a screen?", "When do you need to read carefully, and when not?", "Do you prefer scanning or detailed reading?"]},
    {"topic": "Sports team", "questions": ["Have you ever been part of a sports team?", "Are team sports popular in your culture?", "Do you like watching team games? Why?", "What are the differences between team sports and individual sports?"]},
    {"topic": "Walking", "questions": ["Do you walk a lot?", "Did you often go outside to have a walk when you were a child?", "Why do people like to walk in parks?", "Where would you like to take a long walk if you had the chance?", "Where did you go for a walk lately?"]},
    {"topic": "Typing", "questions": ["Do you prefer typing or handwriting?", "Do you type on a desktop or laptop keyboard every day?", "When did you learn how to type on a keyboard?", "How do you improve your typing?"]},
    {"topic": "Food", "questions": ["What is your favourite food?", "What kind of food did you like when you were young?", "Has your favourite food changed since you were a child?", "Do you eat different foods at different times of the year?"]},
    {"topic": "Hobby", "questions": ["Do you have the same hobbies as your family members?", "Do you have a hobby that you’ve had since childhood?", "Did you have any hobbies when you were a child?", "Do you have any hobbies?"]},
    {"topic": "Life stages", "questions": ["Do you enjoy being the age you are now?", "What did you often do with your friends in your childhood?", "What do you think is the most important at the moment?", "Do you have any plans for the next five years?", "How do people remember each stage of their lives?", "At what age do you think people are the happiest?"]},
    {"topic": "Gifts", "questions": ["What gift have you received recently?", "Have you ever sent handmade gifts to others?", "Have you ever received a great gift?", "What do you consider when choosing a gift?", "Do you think you are good at choosing gifts?"]},
    {"topic": "The city you live in", "questions": ["Would you recommend your city to others?", "What’s the weather like where you live?", "Are there people of different ages living in this city?", "Are the people friendly in the city?", "Is the city friendly to children and old people?", "Do you often see your neighbors?", "What city do you live in?", "Do you like this city? Why?", "How long have you lived in this city?", "Are there big changes in this city?", "Is this city your permanent residence?"]},
    {"topic": "Day off", "questions": ["When was the last time you had a few days off?", "What do you usually do when you have days off?", "Do you usually spend your days off with your friends", "What would you like to do if you had a day off tomorrow?"]},
    {"topic": "Morning time", "questions": ["Do you like getting up early in the morning?", "What do you usually do in the morning?", "What did you do in the morning when you were little? Why?", "Are there any differences between what you do in the morning now and what you did in the past?", "Do you spend your mornings doing the same things on both weekends and weekdays? Why?"]},
    {"topic": "Dreams", "questions": ["Can you remember the dreams you had?", "Do you share your dreams with others?", "Do you think dreams have special meanings?", "Do you want to make your dreams come true?"]},
    {"topic": "Pets and Animals", "questions": ["What’s your favourite animal? Why?", "Where do you prefer to keep your pet, indoors or outdoors?", "Have you ever had a pet before?", "What is the most popular animal in Vietnam?"]},
    {"topic": "Work or studies", "questions": ["What subjects are you studying?", "Do you like your subject?", "Why did you choose to study that subject?", "Do you think that your subject is popular in your country?", "Do you have any plans for your studies in the next five years?", "What are the benefits of being your age?", "Do you want to change your major?", "Do you prefer to study in the mornings or in the afternoons?", "How much time do you spend on your studies each week?", "Are you looking forward to working?", "What technology do you use when you study?", "What changes would you like to see in your school?", "What work do you do?", "Why did you choose to do that type of work (or that job)?", "Do you like your job?", "What requirements did you need to meet to get your current job?", "Do you have any plans for your work in the next five years?", "What do you think is the most important at the moment?", "Do you want to change to another job?", "Do you miss being a student?", "What technology do you use at work?", "Who helps you the most? And how?"]},
    {"topic": "Home & Accommodation", "questions": ["Who do you live with?", "Do you live in an apartment or a house?", "What part of your home do you like the most?", "What’s the difference between where you are living now and where you have lived in the past?", "What kind of house or apartment do you want to live in in the future?", "What room does your family spend most of the time in?", "What do you usually do in your apartment?", "What kinds of accommodation do you live in?", "Do you plan to live there for a long time?", "Can you describe the place where you live?", "Do you prefer living in a house or an apartment?", "Please describe the room you live in.", "What’s your favorite room in your apartment or house？", "What makes you feel pleasant in your home？", "How long have you lived there?", "Do you think it is important to live in a comfortable environment？"]},
    {"topic": "Hometown", "questions": ["Have you learned anything about the history of your hometown?", "Did you learn about the culture of your hometown in your childhood?", "Is that a big city or a small place?", "Do you like your hometown?", "What do you like (most) about your hometown?", "Is there anything you dislike about it?", "How long have you been living there?", "Do you like living there?", "Please describe your hometown a little.", "What’s your hometown famous for?", "Did you learn about the history of your hometown at school?", "Are there many young people in your hometown?", "Is your hometown a good place for young people to pursue their careers?"]},
    {"topic": "The area you live in", "questions": ["Do you live in a noisy or a quiet area?", "Are the people in your neighborhood nice and friendly?", "Do you like the area that you live in?", "Where do you like to go in that area?", "Do you know any famous people in your area?", "What are some changes in the area recently?", "Do you know any of your neighbours?"]},
    {"topic": "Keys", "questions": ["Do you always bring a lot of keys with you?", "Have you ever lost your keys？", "Do you often forget the keys and lock yourself out？", "Do you think it’s a good idea to leave your keys with a neighbour?"]},
    {"topic": "Doing something well", "questions": ["Do you have an experience when you did something well?", "Do you have an experience when your teacher thought you did a good job?", "Do you often tell your friends when they do something well?"]},
    {"topic": "Rules", "questions": ["Are there any rules for students at your school?", "Do you think students would benefit more from more rules?", "Have you ever had a really dedicated teacher?", "Do you prefer to have more or fewer rules at school?"]},
    {"topic": "Public places", "questions": ["Have you ever talked with someone you don’t know in public places?", "Do you wear headphones in public places?", "Would you like to see more public places near where you live?", "Do you often go to public places with your friends?"]},
    {"topic": "Staying with old people", "questions": ["Have you ever worked with old people?", "Are you happy to work with people who are older than you?", "Do you enjoy spending time with old people?", "What are the benefits of being friends with or working with old people?"]},
    {"topic": "Growing vegetables/fruits", "questions": ["Are you interested in growing vegetables and fruits?", "Is growing vegetables popular in your country?", "Do many people grow vegetables in your city?", "Do you think it’s easy to grow vegetables?", "Should schools teach students how to grow vegetables?"]},
    {"topic": "Going out", "questions": ["Do you bring food or snacks with you when going out?", "Do you always take your mobile phone with you when going out?", "Do you often bring cash with you?", "How often do you use cash?"]},
    {"topic": "Advertisements", "questions": ["Do you often see advertisements when you are on your phone or computer?", "Is there an advertisement that made an impression on you when you were a child?", "Do you see a lot of advertising on trains or other transport?", "Do you like advertisements?", "What kind of advertising do you like?"]},
    {"topic": "Crowded place", "questions": ["Is the city where you live crowded?", "Is there a crowded place near where you live?", "Do you like crowded places?", "Do most people like crowded places?", "When was the last time you were in a crowded place?"]},
    {"topic": "Chatting", "questions": ["Do you like chatting with friends?", "What do you usually chat about with friends?", "Do you prefer to chat with a group of people or with only one friend?", "Do you prefer to communicate face-to-face or via social media?", "Do you argue with friends?"]},
    {"topic": "Friends", "questions": ["Is there a difference between where you meet friends now and where you used to meet them in the past?", "Why are some places suitable for meeting while others are not?", "Do you prefer to spend time with one friend or with a group of friends?", "Would you invite friends to your home?", "How important are friends to you?", "Do you often go out with your friends?", "Where do you often meet each other?", "What do you usually do with your friends?", "Do you have a friend you have known for a long time?"]},
    {"topic": "Shoes", "questions": ["Do you like buying shoes? How often?", "Have you ever bought shoes online?", "How much money do you usually spend on shoes?", "Which do you prefer, fashionable shoes or comfortable shoes?"]},
    {"topic": "Museums", "questions": ["Do you think museums are important?", "Are there many museums in your hometown?", "Do you often visit museums?", "When was the last time you visited a museum?"]},
    {"topic": "Having a break", "questions": ["How often do you take a rest or a break?", "What do you usually do when you are resting?", "Do you take a nap when you are taking your rest?", "How do you feel after taking a nap?"]},
    {"topic": "Borrowing/lending things", "questions": ["Do you mind if others borrow money from you?", "How do you feel when people don’t return things they borrowed from you?", "Do you like to lend things to others?", "Have you ever borrowed money from others?", "Have you borrowed books from others?"]},
    {"topic": "Sharing things", "questions": ["Who is the first person you would like to share good news with?", "Do you prefer to share news with your friends or your parents?", "Do you have anything to share with others recently?", "What kind of things are not suitable for sharing?", "What kind of things do you like to share with others?", "Did your parents teach you to share when you were a child?"]},
    {"topic": "Plants", "questions": ["Do you keep plants at home?", "What plant did you grow when you were young?", "Do you know anything about growing a plant?", "Do Chinese people send plants as gifts?"]},

    # Part 2 & 3
    {"topic": "Special cake", "part2": "Describe a special cake you received from others", "part3": ["In your country, do people nowadays cook at home as frequently as people did in the past?", "What do you think of people using their mobile phones during a meal?", "What are the differences between special food in Vietnam and other countries?", "Is there any food in your country that is eaten at special times or on special occasions?", "Why are some people willing to spend a lot of money on meals on special days?", "Do you think it’s good to communicate when eating with your family?"]},
    {"topic": "City enjoyed visiting", "part2": "Describe a city you enjoyed visiting", "part3": ["What kinds of facilities do big cities have?", "Do you think modern cities are suitable for young people or old people?", "Before you travel to a city, what factors would you consider?", "What are the disadvantages of living in a very famous city?", "Do you prefer to visit well-developed cities or cities with a long history?", "For those who live in cities, is it because they want to or have to?"]},
    {"topic": "Natural world lover", "part2": "Describe a person who likes to look after the natural world", "part3": ["Do you think parents should teach their children how to protect the environment?", "What laws about the environment are effective in your country?", "Which do you think people prefer, rewards or punishment, when it comes to government intervention in environmental protection?", "Is it easy for children in cities to get close to the natural world?", "What can people do to protect the natural world?", "Is it important to teach students environmental protection at school?"]},
    {"topic": "Short-term job abroad", "part2": "Describe a short-term job you want to have in a foreign country", "part3": ["What short-term jobs do young people do in other countries?", "What challenges do young people face when working abroad?", "What are the benefits of working for an international company?", "What personal skills are required to work in an international company?", "What kind of work can young people do in foreign countries?", "Why are some people unwilling to work in other countries?"]},
    {"topic": "Advice given", "part2": "Describe a time when you gave advice to others", "part3": ["Should people prepare before giving advice?", "Is it good to ask advice from strangers online?", "What are the personalities of people whose job is to give advice to others?", "What are the problems if you ask too many people for advice?", "Why do some people think it is better to ask for advice from friends than from parents?", "When would old people ask young people for advice?"]},
    {"topic": "Helpful person", "part2": "Describe a person who often helps others", "part3": ["Do you think schools should teach children to do household chores?", "Why are employees reluctant to ask their managers for help?", "What can children do to help their parents?", "Should children help their parents with household chores?", "What kind of help do people need when looking for a new job?", "Who should people ask for help, colleagues or family members?"]},
    {"topic": "Bad music event", "part2": "Describe an event you attended in which you didn’t enjoy the music played", "part3": ["What kind of music events do people like today?", "Do you think children should receive some musical education?", "What are the differences between old and young people’s music preferences?", "What kind of music events are there in your country?"]},
    {"topic": "Self-taught friend", "part2": "Describe one of your friends who learned something without a teacher", "part3": ["Is it necessary to keep learning after graduating from school?", "Should teachers make learning in their classes fun?", "Do you think there are too many subjects for students to learn?", "Is it better to focus on a few subjects or to learn many subjects?", "Do you think enterprises should provide training for their employees?", "Do you think it is good for older adults to continue learning?"]},
    {"topic": "Technology wish", "part2": "Describe a piece of technology (not a phone) that you would like to own", "part3": ["What are the differences between the technology of the past and that of today?", "What technology do young people like to use?", "What are the differences between online and face-to-face communication?", "Do you think technology has changed the way people communicate?", "What negative effects does technology have on people’s relationships?", "What are the differences between making friends in real life and online?"]},
    {"topic": "Perfect job", "part2": "Describe a perfect job you would like to have in the future", "part3": ["What kind of job can be called a ‘dream job’?", "What jobs do children want to do when they grow up?", "Do people’s ideal jobs change as they grow up?", "What should people consider when choosing jobs?", "Is salary the main reason why people choose a certain job?", "What kind of jobs are the most popular in your country?"]},
    {"topic": "Child drawing", "part2": "Describe a child who loves drawing/painting", "part3": ["What is the right age for a child to learn drawing?", "Why do most children draw more often than adults do?", "Why do some people visit galleries or museums instead of viewing artworks online?", "Do you think galleries and museums should be free of charge?", "How do artworks inspire people?", "What are the differences between reading a book and visiting a museum?"]},
    {"topic": "App or program", "part2": "Describe a program or app on your computer or phone", "part3": ["What are the differences between old and young people when using apps?", "Why do some people not like using apps?", "What apps are popular in your country? Why?", "Should parents limit their children’s use of computer programs and computer games? Why and how?", "Do you think young people are more and more reliant on these programs?"]},
    {"topic": "Planner person", "part2": "Describe a person who makes plans a lot and is good at planning", "part3": ["Do you think it’s important to plan ahead?", "Do you think children should plan their future careers?", "Is making study plans popular among young people?", "Do you think choosing a college major is closely related to a person’s future career?"]},
    {"topic": "Family heirloom", "part2": "Describe something important that has been kept in your family for a long time", "part3": ["What things do families keep for a long time?", "What’s the difference between things valued by people in the past and today?", "What kinds of things are kept in museums?", "What’s the influence of technology on museums?"]},
    {"topic": "Famous person meet", "part2": "Describe a famous person you would like to meet", "part3": ["What are the advantages and disadvantages of being a famous child?", "What can today’s children do to become famous?", "What can children do with their fame?", "Do people become famous because of their talent?"]},
    {"topic": "Interesting building", "part2": "Describe an interesting building", "part3": ["Do you think it’s reasonable to charge an entry fee for visiting interesting buildings?", "Is it better to live in a new building or an old one?", "What types of buildings are popular in your country?", "Is it worth spending a lot of money on the exterior appearance of a building?", "Is it more important for a building to look good on the outside or on the inside?", "Why do people like to visit historical sites?"]},
    {"topic": "Movie enjoyed", "part2": "Describe a movie you watched and enjoyed recently", "part3": ["What kinds of movies do you think are successful in your country?", "What are the factors that make a successful movie?", "Do Vietnamese people prefer to watch domestic movies or foreign movies?", "Do you think only well-known directors can create the best movies?", "Do you think successful movies should have well-known actors or actresses in leading roles?", "Why do people prefer to watch movies in the cinema?"]},
    {"topic": "Essential item", "part2": "Describe something that you can’t live without (not a computer/phone)", "part3": ["Why do all children like toys?", "Do you think it is good for a child to always take his or her favourite toy with them all the time?", "Why are children attracted to new things (such as electronics)?", "Why do some grown-ups hate to throw out old things (such as clothes)?", "Is the way people buy things affected? How?", "What do you think influences people to buy new things?"]},
    {"topic": "Famous city", "part2": "Describe a city that you think is very interesting/famous", "part3": ["What advantages can tourism bring to a city?", "Why do some young people like to live in cities?", "Do most elderly people live in the city or in the countryside?", "Do you think well-developed tourism will have negative effects on local people?", "What are the benefits of urbanization?", "Do you think the big cities in Vietnam today will become even larger in the future?"]},
    {"topic": "Expensive item", "part2": "Describe an item on which you spent more than expected", "part3": ["Do you think it is the rich people’s responsibility to donate money to people in need?", "What kind of things are people happy to pay a high price for?", "Do you often buy more than you expected?", "What do you think young people spend most of their money on?", "Do you think it is important to save money? Why?", "Do people buy things they don’t need?"]},
    {"topic": "Proud family member", "part2": "Describe a time when you felt proud of a family member", "part3": ["When would parents feel proud of their children?", "Should parents reward children? Why and how?", "Is it good to reward children too often? Why?", "On what occasions would adults be proud of themselves?"]},
    {"topic": "Road trip", "part2": "Describe a bicycle/motorcycle/car trip you would like to go", "part3": ["Which form of vehicle is more popular in your country, bikes, cars or motorcycles?", "Do you think air pollution comes mostly from mobile vehicles?", "Do you think people need to change the way of transportation drastically to protect the environment?", "Why do people prefer to travel by car?", "How are the transportation systems in urban areas and rural areas different?"]},
    {"topic": "Smart problem solver", "part2": "Describe a person who solved a problem in a smart way", "part3": ["Do you think smart children are happier than other children?", "Is it important for schools to identify and develop each student’s talents?", "Do you think children are born smart or they learn to become smart?", "How do children become smart at school?", "Why are some people well-rounded and others only good at one thing?", "Why does modern society need talents of all kinds?"]},
    {"topic": "Smiling occasion", "part2": "Describe an occasion when many people were smiling", "part3": ["Do people smile more when they are younger or older?", "Do you think people who like to smile are more friendly?", "Why do most people smile in photographs?", "Do women smile more than men? Why?"]},
    {"topic": "No mobile phone", "part2": "Describe an occasion when you were not allowed to use your mobile phone", "part3": ["How do young and old people use mobile phones differently?", "What positive and negative impact do mobile phones have on friendship?", "Is it a waste of time to take pictures with mobile phones?", "Do you think it is necessary to have laws on the use of mobile phones?"]},
    {"topic": "Encouragement given", "part2": "Describe a time when you encouraged someone to do something that he/she didn’t want to do", "part3": ["Should children do everything their parents ask them to do?", "How can employers encourage their staff?", "How can leaders encourage their employees?", "When should parents encourage their children?", "What kind of encouragement should parents give?", "Do you think some people are better than others at persuading?"]},
    {"topic": "Imagination used", "part2": "Describe a time you needed to use your imagination", "part3": ["Do you think adults can have lots of imagination?", "Do you think imagination is essential for scientists?", "What kinds of jobs need imagination?", "What subjects are helpful for children’s imagination?", "What games help develop children’s imagination?", "How important is imagination to children?"]},
    {"topic": "Disappointing movie", "part2": "Describe a movie you watched recently that you felt disappointed about", "part3": ["Do you believe movie reviews?", "What are the different types of films in your country?", "Are historical films popular in your country? Why?", "Do you think films with famous actors or actresses are more likely to become successful films?", "Why are Japanese animated films so popular?", "Should the director pay a lot of money to famous actors?"]},
    {"topic": "Relax place", "part2": "Describe your favorite place in your house where you can relax", "part3": ["Why is it difficult for some people to relax?", "What are the benefits of doing exercise?", "Do people in your country exercise after work?", "What is the place where people spend most of their time at home?", "Do you think there should be classes for training young people and children how to relax?", "Which is more important, mental relaxation or physical relaxation?"]},
    {"topic": "Useful book", "part2": "Describe a book you read that you found useful", "part3": ["What are the types of books that young people like to read?", "What should the government do to make libraries better?", "Do you think old people spend more time reading than young people?", "Which one is better, paper books or e-books?", "Have libraries changed a lot with the development of the internet?", "What should we do to prevent modern libraries from closing down?"]},
    {"topic": "Popular person", "part2": "Describe a popular person", "part3": ["Why are some students popular in school?", "Is it important for a teacher to be popular?", "Do you think good teachers are always popular among students?", "What are the qualities of being a good teacher?", "Is it easier to become popular nowadays?", "Why do people want to be popular?"]},
    {"topic": "Creative person", "part2": "Describe a creative person (e.g. an artist, a musician, an architect, etc.) you admire", "part3": ["Do you think children should learn to play musical instruments?", "How do artists acquire inspiration?", "Do you think pictures and videos in news reports are important?", "What can we do to help children stay creative?", "How does drawing help to enhance children’s creativity?", "What kind of jobs require creativity?"]},
    {"topic": "Long journey", "part2": "Describe a long journey you had and would like to take again", "part3": ["Do you think it is a good choice to travel by plane?", "What are the differences between group travelling and travelling alone?", "What do we need to prepare for a long journey?", "Why do some people like making long journeys?", "Why do some people prefer to travel in their own country?", "Why do some people prefer to travel abroad?"]},
    {"topic": "Family business person", "part2": "Describe a person you know who enjoys working for a family business (e.g. a shop, etc.)", "part3": ["Would you like to start a family business?", "Would you like to work for a family business?", "Why do some people choose to start their own company?", "What are the advantages and disadvantages of family businesses?", "What family businesses do you know in your local area?", "What makes a successful family business?"]},
    {"topic": "Wild animal learn", "part2": "Describe a wild animal that you want to learn more about", "part3": ["Why should we protect wild animals?", "Why are some people more willing to protect wild animals than others?", "Do you think it’s important to take children to the zoo to see animals?", "Why do some people attach more importance to protecting rare animals?", "Should people educate children to protect wild animals?", "Is it more important to protect wild animals or the environment?"]},
    {"topic": "Broken item", "part2": "Describe a time when you broke something", "part3": ["What kind of things are more likely to be broken by people at home?", "What kind of people like to fix things by themselves?", "Do you think clothes produced in the factory are of better quality than those made by hand?", "Do you think handmade clothes are more valuable?", "Is the older generation better at fixing things?", "Do you think elderly people should teach young people how to fix things?"]},
    {"topic": "Important friend", "part2": "Describe a good friend who is important to you", "part3": ["How do children make friends at school?", "How do children make friends when they are not at school?", "Do you think it is better for children to have a few close friends or many casual friends?", "Do you think a child’s relationship with friends can be replaced by that with other people, like parents or other family members?", "What are the differences between friends made inside and outside the workplace?", "Do you think it’s possible for bosses and their employees to become friends?"]},
    {"topic": "Musical friend", "part2": "Describe a friend of yours who is good at music/singing", "part3": ["What kind of music is popular in your country?", "What kind of music do young people like?", "What are the differences between young people’s and old people’s preferences in music?", "What are the benefits of children learning a musical instrument?", "Do you know what kind of music children like today?", "Do you think the government should invest more money in concerts?"]},
    {"topic": "Great dinner", "part2": "Describe a great dinner you and your friends or family members enjoyed", "part3": ["Do people prefer to eat out at restaurants or eat at home during the Spring Festival?", "What food do you eat on special occasions, like during the Spring Festival or the Mid-autumn Festival?", "Why do people like to have meals together during important festivals?", "Is it a hassle to prepare a meal at home?", "What do people often talk about during meals?", "People are spending less and less time having meals with their families these days. Is this good or bad?"]},
    {"topic": "Important decision with help", "part2": "Describe an important decision made with the help of other people", "part3": ["What kind of decisions do you think are meaningful?", "What important decisions should be made by teenagers themselves?", "Why are some people unwilling to make quick decisions?", "Do people like to ask for advice more for their personal life or their work?", "Why do some people like to ask others for advice?"]},
    {"topic": "Power cut", "part2": "Describe a time when the electricity suddenly went off", "part3": ["Which is better, electric bicycles or ordinary bicycles?", "Do you think electric bicycles will replace ordinary bicycles in the future?", "Which is better, electric cars or petrol cars?", "How did people manage to live without electricity in the ancient world?", "Is it difficult for the government to replace all the petrol cars with electric cars?", "Do people use more electricity now than before?"]},
    {"topic": "Exciting activity", "part2": "Describe an exciting activity you have tried for the first time", "part3": ["Why are some people unwilling to try new things?", "Do you think fear stops people from trying new things?", "Why are some people keen on doing dangerous activities?", "Do you think that children adapt to new things more easily than adults?", "What can people learn from doing dangerous activities?", "What are the benefits of trying new things?"]},
    {"topic": "Traditional story", "part2": "Describe an interesting traditional story", "part3": ["What kind of stories do children like?", "What are the benefits of listening to stories before bed?", "Why do most children like listening to stories before bedtime?", "What can children learn from stories?", "Do all stories for children have happy endings?", "Is a good storyline important for a movie?"]},
    {"topic": "Old person interesting", "part2": "Describe an old person who has an interesting life and you enjoy talking to him/her", "part3": ["Should companies employ older workers?", "What do you think older people can contribute at work?", "Why do governments make retirement policies?", "When do you think is the best time to retire?", "Do you think people should spend more time with their grandparents?", "Is it beneficial to live with elderly people?"]},
    {"topic": "Something in sky", "part2": "Describe a time when you saw something in the sky (e.g. flying kites, birds, sunset, etc.)", "part3": ["Would people be willing to get up early to watch and enjoy the sunrise?", "When would people watch the sky?", "Do many people pay attention to the shapes of stars?", "What do people usually see in the sky in the daytime?", "What are the differences between things people see in the sky in the daytime and at night?", "Why do some people like to watch stars at night?"]},
    {"topic": "Routine change", "part2": "Describe a positive change that you have made recently in your daily routine", "part3": ["What do people normally plan in their daily lives?", "Is time management very important in our daily lives?", "What changes would people often make?", "Do you think it is good to change jobs frequently?", "Who do you think would make changes more often, young people or old people?", "Who should get more promotion opportunities in the workplace, young people or older people?"]},
    {"topic": "Good service", "part2": "Describe a time when you received good service in a shop/store", "part3": ["Why are shopping malls so popular in Vietnam?", "What are the advantages and disadvantages of shopping in small shops?", "Why do some people not like shopping in small shops?", "What are the differences between online shopping and in-store shopping?", "What are the advantages and disadvantages of shopping online?", "Can consumption drive economic growth?"]},
    {"topic": "Natural place", "part2": "Describe a natural place (e.g. parks, mountains, etc.)", "part3": ["What kind of people like to visit natural places?", "What are the differences between a natural place and a city?", "Do you think that going to the park is the only way to get close to nature?", "What can people gain from going to natural places?", "Are there any wild animals in the city?", "Do you think it is a good idea to let animals stay in local parks for people to see?"]},
    {"topic": "Successful sportsperson", "part2": "Describe a successful sportsperson you admire", "part3": ["Should students have physical education and do sports at school?", "What qualities should an athlete have?", "Is talent important in sports?", "Is it easy to identify children’s talents?", "What is the most popular sport in your country?", "Why are there so few top athletes?"]},
    {"topic": "Science area", "part2": "Describe an area/subject of science (biology, robotics, etc.) that you are interested in and would like to learn more about", "part3": ["Why do some children not like learning science at school?", "Is it important to study science at school?", "Which science subject is the most important for children to learn?", "Should people continue to study science after graduating from school?", "How do you get to know about scientific news?", "Should scientists explain the research process to the public?"]},
    {"topic": "Unusual meal", "part2": "Describe an unusual meal you had", "part3": ["What are the advantages and disadvantages of eating in restaurants?", "What fast food are there in your country?", "Do people eat fast food at home?", "Why do some people choose to eat out instead of ordering takeout?", "Do people in your country socialize in restaurants? Why?", "Do people in your country value food culture?"]},
    {"topic": "Good habit friend", "part2": "Describe a good habit your friend has and you want to develop", "part3": ["How do we develop bad habits?", "What can we do to get rid of bad habits?", "What habits should children have?", "What should parents do to teach their children good habits?", "What influences do children with bad habits have on other children?", "Why do some habits change when people get older?"]},
    {"topic": "Waiting special", "part2": "Describe a time when you waited for something special that would happen", "part3": ["Why are some people unwilling to wait?", "Where do children learn to be patient, at home or at school?", "On what occasions do people usually need to wait?", "Who behave better when waiting, children or adults?", "Compared to the past, are people less patient now？Why?", "What are the positive and negative effects of waiting on society？"]},
    {"topic": "Social media interesting", "part2": "Describe a time you saw something interesting on social media", "part3": ["Why do people like to use social media?", "What kinds of things are popular on social media?", "What are the advantages and disadvantages of using social media?", "What do you think of making friends on social network?", "Are there any people who shouldn’t use social media?", "Do you think people spend too much time on social media?"]},
    {"topic": "Natural talent improve", "part2": "Describe a natural talent (sports, music, etc.) you want to improve", "part3": ["Do you think artists with talents should focus on their talents?", "Is it possible for us to know whether children who are 3 or 4 years old will become musicians and painters when they grow up?", "Why do people like to watch talent shows？", "Do you think it is more interesting to watch famous people’s or ordinary people’s shows?"]},
    {"topic": "Childhood toy", "part2": "Describe a toy you liked in your childhood", "part3": ["What’s the difference between the toys boys play with and girls play with?", "What are the advantages and disadvantages of modern toys?", "How do advertisements influence children?", "Should advertising aimed at kids be prohibited?", "What’s the difference between the toys kids play now and those they played in the past?", "Do you think parents should buy more toys for their kids or spend more time with them?"]},
    {"topic": "Foreign language talk", "part2": "Describe the time when you first talked in a foreign language", "part3": ["Does learning a foreign language help in finding a job?", "Which stage of life do you think is the best for learning a foreign language?", "At what age should children start learning a foreign language?", "Which skill is more important, speaking or writing ?", "Does a person still need to learn other languages, if he or she is good at English?", "Do you think minority languages will disappear?"]},
    {"topic": "Lost way", "part2": "Describe an occasion when you lost your way", "part3": ["Is a paper map still necessary?", "How do people react when they get lost?", "Why do some people get lost more easily than others?", "Do you think it is important to be able to read a map?", "Do you think it is important to do some preparation before you travel to new places?", "How can people find their way when they are lost?"]},
    {"topic": "Apology received", "part2": "Describe a time when someone apologized to you", "part3": ["Do you think every “sorry” is from the bottom of the heart?", "Are women better than men at recognizing emotions?", "On what occasion do people usually apologize to others?", "Do people in your country like to say “sorry”?", "Do you think people should apologize for anything wrong they do?", "Why do some people refuse to say “sorry” to others?"]}
]

def enqueue_question(qid, question):
    # Enqueue Barem Band 8
    requests.post(f"{SERVER_URL}/enqueue_barem", json={"id": qid, "question": question, "band": 8})
    
    # Chia nhỏ Vocab thành 2 đợt, mỗi đợt 5 từ (Tổng 10)
    for i in range(2):
        requests.post(f"{SERVER_URL}/enqueue_vocab", json={
            "id": f"{qid}_v{i+1}", 
            "question": question, 
            "count": 5, 
            "vocab_type": "vocabulary",
            "chunk": i + 1
        })
        
    # Chia nhỏ Collocations thành 2 đợt, mỗi đợt 5 từ (Tổng 10)
    for i in range(2):
        requests.post(f"{SERVER_URL}/enqueue_vocab", json={
            "id": f"{qid}_c{i+1}", 
            "question": question, 
            "count": 5, 
            "vocab_type": "collocation",
            "chunk": i + 1
        })
        
    # Chia nhỏ Idioms thành 2 đợt, mỗi đợt 5 từ (Tổng 10)
    for i in range(2):
        requests.post(f"{SERVER_URL}/enqueue_vocab", json={
            "id": f"{qid}_id{i+1}", 
            "question": question, 
            "count": 5, 
            "vocab_type": "idiom",
            "chunk": i + 1
        })

total_questions = 0
for entry in data_q2:
    topic = entry['topic']
    
    # Part 1
    if 'questions' in entry:
        for i, q in enumerate(entry['questions']):
            qid = f"Q2_P1_{topic.replace(' ', '_')}_{i+1}"
            enqueue_question(qid, f"Part 1 - Topic {topic}: {q}")
            total_questions += 1
            
    # Part 2
    if 'part2' in entry:
        qid_p2 = f"Q2_P2_{topic.replace(' ', '_')}"
        enqueue_question(qid_p2, f"Part 2: {entry['part2']}")
        total_questions += 1
        
        # Part 3
        for i, q in enumerate(entry['part3']):
            qid_p3 = f"Q2_P3_{topic.replace(' ', '_')}_{i+1}"
            enqueue_question(qid_p3, f"Part 3 - Related to {topic}: {q}")
            total_questions += 1

print(f"Successfully enqueued tasks for {total_questions} questions (x4 tasks per question).")
